version: '3.1'

services:
  springboot:
    image: aretimadhusudhan/spring-boot-mongo:1
    environment:
    - MONGO_DB_HOSTNAME=mongodb
    - MONGO_DB_USERNAME=madhu
    - MONGO_DB_PASSWORD=madhu123
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongodb
    networks:
    - aws

  mongodb:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=madhu
    - MONGO_INITDB_ROOT_PASSWORD=madhu123
    volumes:
      - aws:/data/db
    restart: always
    networks:
    - aws
    
volumes:
  aws:
    external: true
    
networks:
  aws:
    external: true
